name: Preview Build
on:
  pull_request:
    branches:
      - staging
      - main
      - dev
    paths:
      - "kofta/**"
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        working-directory: ./kofta
        run: npm install

      - name: Build
        working-directory: ./kofta
        run: npm run build

      - name: Prepare deploy
        working-directory: ./kofta
        env:
          PRNUMBER: $(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        run: |
          git clone https://github.com/cloudflare/worker-sites-template
          mv worker-sites-template/workers-site .
          cat << EOF > wrangler.toml
          name = "dogehouse-pr-$PRNUMBER"
          type = "webpack"
          account_id = "$CF_ACCOUNT_ID"
          workers_dev = true
          route = ""
          zone_id = "$CF_ZONE_ID"

          [site]
          bucket = "./build"
          EOF
          cat wrangler.toml

      - name: Deploy
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "kofta"
